version: '2'
services:
  zookeeper:
    image: dipakpravin87/zookeeper:v3.4.9
    ports:
      - "2181:2181"
  kafka:
    image: dipakpravin87/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  spark-master:
    image: dipakpravin87/spark-master:2.4.5
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: dipakpravin87/spark-worker:2.4.5
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  transaction-streamer-processor:
    image: dipakpravin87/spark-streamer:final
    container_name: transaction-streamer-processor
    ports :
      - "6060:6060"
    depends_on:
      - spark-worker-1
      - kafka
    links:
      - spark-master:spark-master

