FROM dipakpravin87/spark-scala-template:2.4.5



ENV SPARK_APPLICATION_MAIN_CLASS entry.StreamProcessor
ENV SPARK_SUBMIT_ARGS " --packages org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.5 "
ENV SPARK_APPLICATION_ARGS "kafka:9092"